include(CaQtDMPluginHelpers)

if(CAQTDM_ENABLE_ARCHIVE_SF_PLUGIN)
    add_subdirectory(archiveSF)
endif()

if(CAQTDM_ENABLE_ARCHIVE_HTTP_PLUGIN)
    if(QT_VERSION_MAJOR GREATER 5 OR (QT_VERSION_MAJOR EQUAL 5 AND CAQTDM_QT_VERSION_MINOR_NUM GREATER 14))
        add_subdirectory(archiveHTTP)
    else()
        message(WARNING "archiveHTTP requires Qt >= 5.15; skipping")
    endif()
endif()

if(NOT CAQTDM_ENABLE_MOBILE)
    if(CAQTDM_ENABLE_ARCHIVE_HIPA_PLUGIN)
        add_subdirectory(archiveHIPA)
    endif()
    if(CAQTDM_ENABLE_ARCHIVE_PRO_PLUGIN)
        add_subdirectory(archivePRO)
    endif()
    if(CAQTDM_ENABLE_ARCHIVE_CA_PLUGIN)
        add_subdirectory(archiveCA)
    endif()
endif()
