#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(archiveHTTPLog)
Q_DECLARE_LOGGING_CATEGORY(archiveSFLog)
Q_DECLARE_LOGGING_CATEGORY(bsreadLog)
Q_DECLARE_LOGGING_CATEGORY(demoLog)
Q_DECLARE_LOGGING_CATEGORY(environmentLog)
Q_DECLARE_LOGGING_CATEGORY(epics3Log)
Q_DECLARE_LOGGING_CATEGORY(epics4Log)
Q_DECLARE_LOGGING_CATEGORY(gpsLog)
Q_DECLARE_LOGGING_CATEGORY(modbusLog);

#endif // LOGGINGCATEGORIES_H
