#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(archiveHTTP)
Q_DECLARE_LOGGING_CATEGORY(archiveSF)
Q_DECLARE_LOGGING_CATEGORY(bsread)
Q_DECLARE_LOGGING_CATEGORY(demo)
Q_DECLARE_LOGGING_CATEGORY(environment)
Q_DECLARE_LOGGING_CATEGORY(epics3)
Q_DECLARE_LOGGING_CATEGORY(epics4)
Q_DECLARE_LOGGING_CATEGORY(gps)
Q_DECLARE_LOGGING_CATEGORY(modbus);

#endif // LOGGINGCATEGORIES_H
