#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(caQtDMLog);
Q_DECLARE_LOGGING_CATEGORY(fileOpenWindowLog);
Q_DECLARE_LOGGING_CATEGORY(pipeReaderLog);

#endif // LOGGINGCATEGORIES_H
