#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(caQtDM);
Q_DECLARE_LOGGING_CATEGORY(fileOpenWindow);
Q_DECLARE_LOGGING_CATEGORY(pipeReader);

#endif // LOGGINGCATEGORIES_H
