# FindEpics
# ---------
# Locates EPICS base libraries and creates imported targets:
#   Epics::ca Epics::Com Epics::pvAccess Epics::pvAccessCA
#   Epics::pvData Epics::pvaClient Epics::nt
# Targets are only created for libraries that exist; consumers must check
# with `if(TARGET Epics::xxx)` for the optional pvAccess family.
#
# Inputs (set by caQtDMConfig.cmake):
#   CAQTDM_EPICS_BASE       EPICS base directory (or EPICS_BASE environment)
#   CAQTDM_EPICS_HOST_ARCH  host architecture (or EPICS_HOST_ARCH environment)
#
# Result variables:
#   Epics_INCLUDE_DIR, Epics_LIBRARY_DIR

if(NOT CAQTDM_EPICS_BASE)
    message(FATAL_ERROR "CAQTDM_EPICS_BASE is not set - point it at your EPICS base directory")
endif()

if(NOT CAQTDM_EPICS_HOST_ARCH)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
            set(CAQTDM_EPICS_HOST_ARCH "linux-aarch64")
        elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(CAQTDM_EPICS_HOST_ARCH "linux-x86")
        else()
            set(CAQTDM_EPICS_HOST_ARCH "linux-x86_64")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
            set(CAQTDM_EPICS_HOST_ARCH "freebsd-x86_64")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|x86)$")
            set(CAQTDM_EPICS_HOST_ARCH "freebsd-x86")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
            set(CAQTDM_EPICS_HOST_ARCH "darwin-aarch64")
        else()
            set(CAQTDM_EPICS_HOST_ARCH "darwin-x86_64")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        if(MINGW)
            if(CMAKE_SIZEOF_VOID_P EQUAL 4)
                set(CAQTDM_EPICS_HOST_ARCH "win32-x86-mingw")
            else()
                set(CAQTDM_EPICS_HOST_ARCH "windows-x64-mingw")
            endif()
        elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(CAQTDM_EPICS_HOST_ARCH "win32-x86")
        else()
            set(CAQTDM_EPICS_HOST_ARCH "windows-x64")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
        if(ANDROID_ABI STREQUAL "arm64-v8a")
            set(CAQTDM_EPICS_HOST_ARCH "android-arm64-v8a")
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(CAQTDM_EPICS_HOST_ARCH "ios-arm64")
    else()
        message(FATAL_ERROR "Cannot derive CAQTDM_EPICS_HOST_ARCH for ${CMAKE_SYSTEM_NAME} - set it explicitly")
    endif()
    if(NOT CAQTDM_EPICS_HOST_ARCH)
        message(FATAL_ERROR "Cannot derive CAQTDM_EPICS_HOST_ARCH for ${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}; set CAQTDM_EPICS_HOST_ARCH or EPICS_HOST_ARCH")
    endif()
    message(STATUS "EPICS host architecture derived: ${CAQTDM_EPICS_HOST_ARCH}")
endif()

set(Epics_INCLUDE_DIR "${CAQTDM_EPICS_BASE}/include")
set(Epics_LIBRARY_DIR "${CAQTDM_EPICS_BASE}/lib/${CAQTDM_EPICS_HOST_ARCH}")

if(NOT EXISTS "${Epics_INCLUDE_DIR}")
    message(FATAL_ERROR "EPICS include directory not found: ${Epics_INCLUDE_DIR}")
endif()

# OS/compiler specific include subdirectories (mirrors caQtDM.pri)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_epics_os_dir os/Linux)
    set(_epics_compiler_dir compiler/gcc)
elseif(ANDROID)
    set(_epics_os_dir os/android)
    set(_epics_compiler_dir compiler/clang)
elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(_epics_os_dir os/freebsd)
    set(_epics_compiler_dir compiler/clang)
elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    set(_epics_os_dir os/openbsd)
    set(_epics_compiler_dir compiler/clang)
elseif(IOS)
    set(_epics_os_dir os/iOS)
    set(_epics_compiler_dir compiler/clang)
elseif(APPLE)
    set(_epics_os_dir os/Darwin)
    set(_epics_compiler_dir compiler/clang)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(_epics_os_dir os/win32)
    if(MINGW)
        set(_epics_compiler_dir compiler/gcc)
    else()
        set(_epics_compiler_dir compiler/msvc)
    endif()
endif()
if(_epics_os_dir AND EXISTS "${Epics_INCLUDE_DIR}/${_epics_os_dir}")
    list(APPEND Epics_INCLUDE_DIRS "${Epics_INCLUDE_DIR}/${_epics_os_dir}")
endif()
if(_epics_compiler_dir AND EXISTS "${Epics_INCLUDE_DIR}/${_epics_compiler_dir}")
    list(APPEND Epics_INCLUDE_DIRS "${Epics_INCLUDE_DIR}/${_epics_compiler_dir}")
endif()

function(_epics_make_target name libname)
    if(_epics_${name}_LIBRARY)
        get_filename_component(_cached_epics_dir "${_epics_${name}_LIBRARY}" DIRECTORY)
        if(NOT _cached_epics_dir STREQUAL Epics_LIBRARY_DIR)
            unset(_epics_${name}_LIBRARY CACHE)
        endif()
    endif()
    set(_epics_find_options NO_DEFAULT_PATH)
    if(ANDROID OR IOS)
        # EPICS was built for the target ABI in a staged directory outside
        # the NDK/Xcode sysroot; do not re-root that explicit directory.
        list(APPEND _epics_find_options NO_CMAKE_FIND_ROOT_PATH)
    endif()
    find_library(_epics_${name}_LIBRARY NAMES ${libname}
        HINTS ${Epics_LIBRARY_DIR}
        ${_epics_find_options})
    if(_epics_${name}_LIBRARY)
        add_library(Epics::${name} UNKNOWN IMPORTED)
        set_target_properties(Epics::${name} PROPERTIES
            IMPORTED_LOCATION "${_epics_${name}_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${Epics_INCLUDE_DIR};${Epics_INCLUDE_DIRS}")
    endif()
    mark_as_advanced(_epics_${name}_LIBRARY)
endfunction()

_epics_make_target(ca ca)
_epics_make_target(Com Com)
_epics_make_target(pvAccess pvAccess)
_epics_make_target(pvAccessCA pvAccessCA)
_epics_make_target(pvData pvData)
_epics_make_target(pvaClient pvaClient)
_epics_make_target(nt nt)

if(NOT TARGET Epics::ca OR NOT TARGET Epics::Com)
    message(FATAL_ERROR "EPICS ca/Com libraries not found in ${Epics_LIBRARY_DIR}")
endif()

set(Epics_FOUND TRUE)
message(STATUS "Found EPICS base ${CAQTDM_EPICS_BASE} (${CAQTDM_EPICS_HOST_ARCH})")
