name: caQtDM DEB Package Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'caQtDM_docs/**'
      - 'caQtDM_Tests/**'
  schedule: # Daily at 2am
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build DEB package
    runs-on: ubuntu-latest
    container: ${{ matrix.container-image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container-image: debian:12
            artifact_name: debian-12
          - container-image: ubuntu:22.04
            artifact_name: ubuntu-22.04

    permissions:
      contents: read
      actions: write

    steps:
    - name: Set up build environment
      run: |
        apt-get update
        apt-get install -y git build-essential devscripts dh-make debhelper

    - name: Checkout repository
      uses: actions/checkout@v6
    
    - name: Install dependencies
      run: |
        apt-get install -y \
          libssl-dev libmbedtls-dev \
          libncurses-dev libreadline-dev \
          qtbase5-dev qtbase5-private-dev qt5-qmake libqwt-qt5-dev python3-dev qttools5-dev qttools5-dev libqt5svg5-dev libqt5designer5 libqt5svg5 libqt5x11extras5-dev libzmq3-dev libqt5serialbus5-dev qtpositioning5-dev libqt5positioning5-plugins libqt5location5
    
    - name: Build and install Qt OPC UA DEB
      run: |
        set -e
        cd caQtDM_Viewer/package/debian/qtopcua
        chmod +x ./create-deb.sh
        ./create-deb.sh
        dpkg -i *.deb

    - name: Build and install epics-base
      run: |
        cd caQtDM_Viewer/package/debian/epics-base
        chmod +x ./create-deb.sh
        ./create-deb.sh
        dpkg -i *.deb

    - name: Build DEB package
      run: |
        cd caQtDM_Viewer/package/debian/caqtdm_qt5
        chmod +x ./create-deb.sh
        ./create-deb.sh --no-checkout
        ls -l *.deb

    - name: Install DEB package
      run: |
        cd caQtDM_Viewer/package/debian/caqtdm_qt5
        dpkg -i *.deb

    - name: Upload Qt OPC UA package as artifact
      uses: actions/upload-artifact@v7
      with:
        name: qtopcua_deb-package-${{ matrix.artifact_name }}
        path: caQtDM_Viewer/package/debian/qtopcua/*.deb

    - name: Upload epics-base package as artifact
      uses: actions/upload-artifact@v7
      with:
        name: epics-base_deb-package-${{ matrix.artifact_name }}
        path: caQtDM_Viewer/package/debian/epics-base/*.deb

    - name: Upload DEB package as artifact
      uses: actions/upload-artifact@v7
      with:
        name: caqtdm_deb-package-${{ matrix.artifact_name }}
        path: caQtDM_Viewer/package/debian/caqtdm_qt5/*.deb

    - name: Verify caQtDM installation
      run: |
        which caQtDM
